branches:
  only:
    - master
    - develop
    - "/^v?[0-9\\.]+/"

cache:
  directories:
    - Carthage

env:
  global:
    - IOS_SCHEME="Punycode-iOS"
    - MACOS_SCHEME="Punycode-macOS"
    - TVOS_SCHEME="Punycode-tvOS"

matrix:
  include:

    # iOS Tests
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=12.1,name=iPhone X" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="YES" CODECOV_FLAG="ios12"
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=11.4,name=iPhone 7 Plus" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" LINT="YES" COVERAGE="NO" CODECOV_FLAG="ios11"
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=10.3.1,name=iPhone 6" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="NO" CODECOV_FLAG="ios10"
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=9.3,name=iPhone 5s" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="NO" CODECOV_FLAG="ios9"

    # tvOS Tests
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=12.1,name=Apple TV 4K" SCHEME="$TVOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="NO" CODECOV_FLAG="tvos12"
#    - os: osx
#      language: objective-c
#      osx_image: xcode10.2
#      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=11.4,name=Apple TV 4K" SCHEME="$TVOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="NO" CODECOV_FLAG="tvos11"
#    - os: osx
#      language: objective-c
#      osx_image: xcode10.2
#      env: PROJ="Punycode.xcodeproj" DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="$TVOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="NO" CODECOV_FLAG="tvos10"

    # macOS Tests
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env: PROJ="Punycode.xcodeproj" DESTINATION="arch=x86_64" SCHEME="$MACOS_SCHEME" RUN_TESTS="YES" LINT="NO" COVERAGE="NO" CODECOV_FLAG="macos"

before_install:
  # Working for “Library not loaded: /usr/lib/libauto.dylib”; see:
  #   https://stackoverflow.com/questions/55389080/xcode-10-2-failed-to-run-app-on-simulator-with-ios-10
  #   https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_1_release_notes
  - if [ "${sim_os_version}" == "9.3" ]; then
    sudo mkdir "/Library/Developer/CoreSimulator/Profiles/Runtimes/${sim_os} ${sim_os_version}.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift"
    fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    bundle install;
    pod repo update;
    gem install xcpretty -N --no-document --quiet;
    brew update;
    brew outdated carthage || brew upgrade carthage;
    fi

install:
  - ./install-swiftlint.sh;

script:
  - set -o pipefail
  - swift -version

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    xcodebuild -version;
    xcodebuild -showsdks;
    fi

  - if [ "$RUN_TESTS" == "YES" ]; then
    xcodebuild clean test -project "$PROJ" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES | xcpretty -c;
    elif [ "$RUN_TESTS" == "NO" ]; then
    xcodebuild clean build -project "$PROJ" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release | xcpretty -c;
    fi

  - if [ "$LINT" == "YES" ]; then
    swiftlint;
    carthage build --no-skip-current;
    pod lib lint --verbose;
    fi

after_success:
  - if [ "$COVERAGE" == "YES" ]; then
    bash <(curl -s https://codecov.io/bash) -J 'Punycode' -cF "$CODECOV_FLAG";
    fi
